# the gateway wildcard cert is also used for internal Rauthy TLS
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wildcard-cert-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore

  target:
    name: argocd-server-tls
    creationPolicy: Owner
    deletionPolicy: Retain

  dataFrom:
  - extract:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: placeholder_vault_secret_key
