apiVersion: v1
kind: Service
metadata:
  name: rauthy
spec:
  selector:
    app: rauthy
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443
---
# The headless service is used for the Raft Cluster setup, so Nodes 
# can connect to each other without any load balancer in between.
apiVersion: v1
kind: Service
metadata:
  name: rauthy-headless
spec:
  type: ClusterIP
  clusterIP: None
  # Make sure to only publish them on the headless service 
  # and NOT the one you are using via your reverse proxy!
  publishNotReadyAddresses: true
  sessionAffinity: None
  selector:
    app: rauthy
  ports:
    - name: hiqlite-raft
      protocol: TCP
      port: 8100
      targetPort: 8100
    - name: hiqlite-api
      protocol: TCP
      port: 8200
      targetPort: 8200
---
# The PDB is only necessary for a HA deployment. You can take it out for a single instance.
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rauthy
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: rauthy
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rauthy
  labels:
    app: rauthy
spec:
  serviceName: rauthy-headless
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: rauthy
  template:
    metadata:
      labels:
        app: rauthy
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rauthy
              topologyKey: "kubernetes.io/hostname"
      securityContext:
        fsGroup: 10001
      containers:
        - name: rauthy
          image: ghcr.io/sebadob/rauthy:0.35.1
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8100
            - containerPort: 8200
            - containerPort: 8080
            - containerPort: 8443
          volumeMounts:
            - name: rauthy-data
              mountPath: /app/data
              readOnly: false
            - name: rauthy-config
              mountPath: /app/config.toml
              readOnly: true
              subPath: config.toml
            - name: rauthy-tls
              mountPath: /app/tls
              readOnly: true
          envFrom:
            - secretRef:
                name: rauthy-env-secret
          readinessProbe:
            httpGet:
              scheme: HTTP
              port: 8200
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 2
          livenessProbe:
            httpGet:
              scheme: HTTP
              port: 8080
              path: /auth/v1/health
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 2
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
      volumes:
        - name: rauthy-config
          configMap:
            name: rauthy-config
        - name: rauthy-tls
          secret:
            secretName: wildcard-cert-tls

  volumeClaimTemplates:
    - apiVersion: v1	
      kind: PersistentVolumeClaim	
      metadata:
        name: rauthy-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: {{ .Values.dataStorageSize }}
