apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: wildcard-cert-tls
spec:
  updatePolicy: Replace
  deletionPolicy: None
  secretStoreRefs:
    - name: oci-vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: wildcard-cert-tls
  data:
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: placeholder-vault-secret-key
