apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: oci://docker.io/envoyproxy/gateway-helm
    version: v1.7.1
    releaseName: envoy-gateway
    namespace: envoy-gateway-system
