apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
   - https://github.com/strange-journey/rauthy-controller/releases/download/v0.1.4/rauthy-controller.yaml
patches:
  - target:
      kind: Deployment
      name: rauthy-controller
    path: patches/security-context-fs-group.yaml
