apiVersion: rauthy.io/v1alpha1
kind: OIDCClient
metadata:
  name: syncthing-oidcclient
spec:
  client_id: syncthing
  confidential: true
  name: Syncthing
  client_uri: https://syncthing.example.com
  allowed_origins:
    - https://syncthing.example.com
  redirect_uris:
    - https://syncthing.example.com/oauth2/callback
  post_logout_redirect_uris:
    - https://syncthing.example.com/
  secret_name: syncthing-oidc-secret
  secret_keys:
    client_id: client-id
    client_secret: client-secret
