apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  serviceName: minecraft-server
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: minecraft-server
          image: itzg/minecraft-server:latest
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          env:
            - name: EULA
              value: "TRUE"
          ports:
            - containerPort: 25565
          readinessProbe:
            exec:
              command: [ "/usr/local/bin/mc-monitor", "status", "--host", "localhost" ]
            # Give it i + p * f seconds to be ready, so 120 seconds
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 20
          # Monitor ongoing liveness
          livenessProbe:
            exec:
              command: ["/usr/local/bin/mc-monitor", "status", "--host", "localhost"]
            initialDelaySeconds: 120
            periodSeconds: 60
          resources:
            requests:
              # hugepages-2Mi: 8Gi
              memory: 8Gi
            limits:
              # hugepages-2Mi: 8Gi
              memory: 8Gi
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
              readOnly: false
            # - name: hugepage
              # mountPath: /hugepages
      # volumes:
      #   - name: hugepage
      #     emptyDir:
      #       medium: HugePages-2Mi

  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: minecraft-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 50Gi