apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  annotations:
    "mc-router.itzg.me/externalServerName": "mc.your.domain"
spec: 
  selector:
    app: minecraft-server
  ports:
    - name: mc
      port: 25565
      targetPort: 25565
      protocol: TCP