apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: openebs
    repo: https://openebs.github.io/openebs
    version: 4.4.0
    releaseName: openebs
    namespace: openebs
