apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/rancher/local-path-provisioner//deploy?ref=v0.0.35
patches:
  - target:
      kind: StorageClass
      name: local-path
    patch: |-
      - op: replace
        path: /reclaimPolicy
        value: Retain