apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: rauthy-controller-crds
    repo: https://strange-journey.github.io/rauthy-controller
    version: 0.1.2
    releaseName: rauthy-controller-crds
