apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: kine-tcp
spec:
  parentRefs:
    - name: gateway
      namespace: envoy-gateway-system
      sectionName: placeholder-gateway-section
  rules:
    - backendRefs: 
      - kind: Service
        name: kine-pg
        port: 5432