apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets-operator
resources:
   - https://github.com/external-secrets/external-secrets/releases/download/v2.7.0/external-secrets.yaml
